spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/LabXpert
    username: postgres
    password: 50145014
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: f776b4a0b68440d419d1
            client-secret: 9af46665bcfa1dcdf940480fd0dab26e2d69a89f

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

logging:
  level:
    org.springframework: DEBUG

server:
  port: 8080
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
